package duke.ui;

import duke.Damien;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Window;

/**
 * Controller for Damien's main JavaFX window.
 */
public class MainWindow extends AnchorPane {
    /** The scrollable area containing the conversation. */
    @FXML
    private ScrollPane scrollPane;

    /** The vertical container holding all dialog boxes. */
    @FXML
    private VBox dialogContainer;

    /** The text field where the user enters a command. */
    @FXML
    private TextField userInput;

    /** The button that submits the command in the text field. */
    @FXML
    private Button sendButton;

    /** The chatbot logic used to parse and execute commands. */
    private Damien damien;

    /** Captures chatbot output before it is added to the conversation. */
    private GuiUi guiUi;

    /** The image shown beside messages entered by the user. */
    private final Image userImage = new Image(
            MainWindow.class.getResourceAsStream("/images/DaUser.png"));

    /** The image shown beside Damien's responses. */
    private final Image damienImage = new Image(
            MainWindow.class.getResourceAsStream("/images/DaDuke.png"));

    /**
     * Keeps the latest conversation response visible as the content grows.
     */
    @FXML
    public void initialize() {
        dialogContainer.heightProperty().addListener((observable, oldHeight, newHeight) -> {
            scrollPane.setVvalue(1.0);
        });
    }

    /**
     * Injects the application logic and GUI output sink into this controller.
     *
     * @param damien the chatbot whose commands should be executed
     * @param guiUi the output sink used by the chatbot
     */
    public void setDamien(Damien damien, GuiUi guiUi) {
        assert damien != null && guiUi != null : "The main window needs Damien and its GUI output sink.";
        this.damien = damien;
        this.guiUi = guiUi;
        damien.showWelcome();
        addDamienResponse(guiUi.consumeOutput());
        userInput.requestFocus();
    }

    /**
     * Creates dialog boxes for a submitted command and Damien's response.
     */
    @FXML
    private void handleUserInput() {
        String input = userInput.getText();
        dialogContainer.getChildren().add(DialogBox.getUserDialog(input, userImage));

        boolean isRunning = damien.processCommand(input);
        addDamienResponse(guiUi.consumeOutput());
        userInput.clear();

        if (!isRunning) {
            userInput.setDisable(true);
            sendButton.setDisable(true);
            closeWindow();
        }
    }

    /** Closes the JavaFX window after Damien processes the {@code bye} command. */
    private void closeWindow() {
        if (userInput.getScene() != null) {
            Window window = userInput.getScene().getWindow();
            if (window != null) {
                window.hide();
            }
        }
    }

    /**
     * Adds one chatbot response to the conversation when there is output.
     *
     * @param response the text generated by Damien
     */
    private void addDamienResponse(String response) {
        if (!response.isBlank()) {
            dialogContainer.getChildren().add(DialogBox.getDamienDialog(response, damienImage));
        }
    }
}
